# fortune-spec: &fortune-spec
#   containers:
#     - name: agent
#       image: embarkstudios/fortune
#       command: ["startrek"]
#       resources:
#         requests:
#           cpu: "0.25"
#           memory: "500Mi"
#         limits:
#           cpu: "0.25"
#           memory: "500Mi"

steps:
  - label: "Consulting my :crystal_ball: thats inside my :k8s: pod"
    env:
      BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
    plugins:
      - k8s-job#phw-scaffold:
          pod-spec:
            containers:
              - name: agent
                image: embarkstudios/fortune
                command: ["startrek"]
                resources:
                  requests:
                    cpu: "0.25"
                    memory: "500Mi"
                  limits:
                    cpu: "0.25"
                    memory: "500Mi"
