fortune-spec:
  containers:
    - name: agent
      image: embarkstudios/fortune
      command: ["startrek"]
      resources:
        requests:
          cpu: "0.25"
          memory: "500Mi"
        limits:
          cpu: "0.25"
          memory: "500Mi"

steps:
  - plugins:
    - buildkite/k8s-job#phw-scaffold:
        pod-spec: *fortune-spec
